--- 
- user_administration
- - admin_users
  - groups
  - permissions
  - controllers
  - actions
- catalogs_administrations
- - countries
  - cities
  - states
  - institutions
  - institutiontitles
  - institutions
- configuration_sites
