--- 
- profile
- - general
  - - people
    - addresses
    - citizens
    - people_identifications
  - schoolings
  - jobpositions
  - - jobposition_internal
    - - jobposition_at_institutions
      - user_adscriptions
      - jobposition_logs
    - jobposition_externals
  - user_stimulus
  - updating_current_skills
  - - user_courses
    - userconferences
    - student_theses
  - user_schoolarships
  - memberships
  - user_prizes
  - user_languages
  - user_skills
  - user_settings
  - - change_passwords
    - user_settings
- user_projects
- user_cites
- user_researchlines
- conferences_and_seminaries
- - user_conferencetalks
  - user_seminaries
  - userconference_committees
- publications
- - bookedition_roleinbooks
  - chapterinbook_roleinchapters
  - user_published_articles
  - user_unpublished_articles
  - user_inproceeding_refereeds
  - user_techreports
  - user_inproceeding_unrefereeds
  - reviews
- colaboration_on_publications
- - user_journals
  - user_proceeding_refereeds
  - user_books
- popular_sciences
- - user_newspaperarticles
  - user_popularscienceworks
- diffusions
- human_resources_formation_and_teachings
- - teaching
  - - user_regularcourses
    - user_specialcourses
    - teaching_activities
    - user_teaching_products
  - human_resources_formations
  - - user_theses
    - thesis_jurors
    - tutorial_committees
    - student_advices
- acadvisits
- outreaches
- - professor_advices
  - instadvices
  - user_outreachworks
- institutional_activities
- technical_activities
- - user_techproducts
  - techactivities
- user_credits
- other_activities_or_products
- - activities
  - user_genericworks
- user_reports
- - user_annual_activities_reports
  - user_annual_activities_plans
